### ISSUE TITLE
Unable to run application using docker image

### ISSUE THREAD

**Issue by Janfy** [orachide/heketi-ui#1]
Hi,

I'm trying to run the application using the docker image from docker hub, but the application failed.

Error log is above:

```
Error: No default engine was specified and no extension was provided.
    at new View (/usr/src/app/node_modules/express/lib/view.js:61:11)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
    at /usr/src/app/app.js:48:7
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/app.js:37:3
```

Can you fix it?
Thanks

**Comment by orachide** [comment]
Hello,

Just tried to check if there is something wrong with the following command:
```sh
docker run -e HEKETI_SERVER_URL="http://YOUR_HEKETI_SERVER_URL" -e HEKETI_SERVER_USER="admin" -e HEKETI_SERVER_SECRET="YOUR_HEKETI_ADMIN_SECRET" -p 3001:3000 orachide/heketi-ui
```
The above command works fine. 

After the container started browse to `http://localhost:3001/`, it should be OK

What is exactly the command you used (remove server URL and secret) and let me know.

**Comment by Janfy** [comment]
Checked once again, and tried from a different server but same problem.

```
#  docker run -d --rm -e HEKETI_SERVER_URL="http://www.domain.tld:9876" -e HEKETI_SERVER_USER="admin" -e HEKETI_SERVER_SECRET="mysecretkey" -p 3001:3000 orachide/heketi-ui
f2dad935476f7739c8e58c0b5664a00686adeae8dbb92217b69660b6f395830b

# docker logs -f f2dad

> heketi-ui@1.0.1 start /usr/src/app
> node ./bin/www

Error: No default engine was specified and no extension was provided.
    at new View (/usr/src/app/node_modules/express/lib/view.js:61:11)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
    at /usr/src/app/app.js:48:7
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/app.js:37:3
GET / 404 11.077 ms - 1038
Error: No default engine was specified and no extension was provided.
    at new View (/usr/src/app/node_modules/express/lib/view.js:61:11)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1008:7)
    at /usr/src/app/app.js:48:7
    at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:315:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/app.js:37:3
GET /favicon.ico 404 1.920 ms - 1038

# docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Heketi REST API is up and accessible from container:

```
# docker exec -it f2da bash
root@f2dad935476f:/usr/src/app# curl http://www.domain.tld:9876
Required authorization token not found
```

**Comment by orachide** [comment]
You are totally right :(

I just Fix the Dockerfile, actually `npm build` didn't work during  the image build.

i changed it to `npm run-script build` and now it's OK

PLease pull again the latest image tag and let me know if it's OK

Thanks

**Comment by Janfy** [comment]
Works fine now!
Great job.
Many thanks for your reactivity.
